#to setup various docker container to run them at once
version: '3.8'
services:
  reverse-proxy:
    image: traefik:v2,2
    #enable the web ui and tell traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
    port:
    #Traefik can listen to the Docker events
      - "80:80"
      - "8080:8080"
    volumes:
    #Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  account:
    build:
      context: ./account
      target: builder
    image: account
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.account.rule=Host(`malcorp.test`)&&PathPrefix(`/api/account`)"
    environment:
      - ENV=dev
    volumes:
      - ./account:/go/src/app
      #have to use $$ (double-dollar) so docker doesn't try to subtitute a variable